Repository googleapis/nodejs-network-management, pull requests merged in 2022-11, with the labels that each got.

#93 fix(deps): use google-gax v3.5.2
  package.json
Labels: automerge, api: networkmanagement, size: xs

#99 build: update README for deprecation notice
  README.md
  owlbot.py
Labels: api: networkmanagement, size: s

#100 build: update README for deprecation notice
  README.md
Labels: api: networkmanagement, size: xs
